import { useState } from 'react'
import { Copy, Trash2, X } from 'lucide-react'
import type { GiftWithCategory, SiteSettings } from '../../types/database'
import { supabase } from '../../lib/supabase'

type ReservationType = 'bring_gift' | 'pix'
interface Props { items: GiftWithCategory[]; settings: SiteSettings; onRemove: (id: string) => void; onClose: () => void; onComplete: () => void; onChooseMore: () => void }

export default function GiftCartDrawer({ items, settings, onRemove, onClose, onComplete, onChooseMore }: Props) {
  const [type, setType] = useState<ReservationType | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false)
  const submit = async () => { if (!type) return setError('Escolha como deseja presentear.'); setLoading(true); setError(null); const { data, error: rpcError } = await supabase.rpc('reserve_gift_batch', { p_items: items.map((item) => ({ gift_id: item.id })), p_reservation_type: type }); setLoading(false); if (rpcError) return setError(rpcError.message); const result = data as { success: boolean; error?: string }; if (!result.success) return setError(result.error || 'Não foi possível concluir a reserva.'); setDone(true); onComplete() }
  if (done && type) return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 modal-overlay"><div className="cart-drawer"><button className="cart-close" onClick={onClose}><X /></button><h2>Presentes reservados com sucesso!</h2><p>Obrigado por fazer parte desse momento especial.</p><ul className="cart-success-list">{items.map((item) => <li key={item.id}>{item.name}</li>)}</ul>{type === 'pix' ? <div className="cart-pix"><p>Você pode fazer o Pix usando a chave abaixo.</p><strong>{settings.pix_email || 'Chave Pix não configurada'}</strong>{settings.pix_email && <button onClick={() => navigator.clipboard.writeText(settings.pix_email || '')}><Copy size={15} /> Copiar chave</button>}{settings.pix_qr_code_url && <img src={settings.pix_qr_code_url} alt="QR Code Pix" />}</div> : <p>Você poderá entregar os presentes pessoalmente no dia do evento.</p>}<button className="cart-primary" onClick={onClose}>Voltar para a lista</button></div></div>
  return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 modal-overlay" onClick={(event) => event.target === event.currentTarget && onClose()}><div className="cart-drawer"><button className="cart-close" onClick={onClose}><X /></button><h2>Sua seleção</h2><p>Confira os presentes escolhidos com carinho antes de finalizar.</p><div className="cart-items">{items.map((item) => <article key={item.id}><div>{item.image_url && <img src={item.image_url} alt="" />}</div><span>{item.name}<small>{item.gift_categories?.name || 'Sem categoria'}</small></span><button onClick={() => onRemove(item.id)} aria-label="Remover"><Trash2 size={17} /></button></article>)}</div><button className="cart-secondary" onClick={onChooseMore}>Escolher mais presentes</button><h3>Como deseja presentear?</h3><label className={`cart-option ${type === 'bring_gift' ? 'selected' : ''}`}><input type="radio" name="type" onChange={() => setType('bring_gift')} /> <span>Vou levar no dia<small>Entregarei pessoalmente no evento.</small></span></label><label className={`cart-option ${type === 'pix' ? 'selected' : ''}`}><input type="radio" name="type" onChange={() => setType('pix')} /> <span>Prefiro fazer Pix<small>Reservo agora e faço o Pix depois.</small></span></label>{error && <p className="cart-error">{error}</p>}<button disabled={loading || !items.length} className="cart-primary" onClick={submit}>{loading ? 'Finalizando...' : 'Finalizar reserva'}</button></div></div>
}
